### PR TITLE
Added Julia

### PR DESCRIPTION
**Pull request by Ghruank**
created a folder for Julia for neural networks. Made a basic feedforward neural network architecture in Julia along with an RNN architecture. Updated README.

### CODE REVIEW

**Review by extinctsion — APPROVED** [review]
PR accepted

**Comment by extinctsion** [comment]
It would be better if you would have named the files as done in the python NN folder

**Comment by extinctsion** [comment]
Pls give a star to this repo if you had fun contributing to this repo

**Comment by Ghruank** [comment]
starred, thank you very much. Also would look into more ways of implementing neural nets in Julia and would follow the python NN structure.

**Pull request merged**
